//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int ID_Client { get; set; }
        public string TelNum { get; set; }
        public string Password { get; set; }
        public string BoughtTickets { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
