//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public Film()
        {
            this.ShowingFilm = new HashSet<ShowingFilm>();
        }

        public Film(string name, string description)
        {
            Name = name;
            Description = description;
        }

        public int FilmID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ShowingFilm> ShowingFilm { get; set; }
    }
}
