//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KinoboomEntities1 : DbContext
    {
        public KinoboomEntities1()
            : base("name=KinoboomEntities1")
        {
        }

        private static KinoboomEntities1 _context;
        public static KinoboomEntities1 GetContext()
        {
            if (_context == null)
                _context = new KinoboomEntities1();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Client> Client { get; set; }
        public DbSet<Film> Film { get; set; }
        public DbSet<ShowingFilm> ShowingFilm { get; set; }
        public DbSet<Ticket> Ticket { get; set; }
    }
}
