//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowingFilm
    {
        public ShowingFilm()
        {
            this.Ticket = new HashSet<Ticket>();
        }
        public ShowingFilm(int filmID, string ticketCost)
        {
            FilmID = filmID;
            TicketCost = ticketCost;
        }
        public int ShowingID { get; set; }
        public Nullable<int> FilmID { get; set; }
        public string Date { get; set; }
        public Nullable<int> SeatsNum { get; set; }
        public string MaxCapacity { get; set; }
        public string TicketCost { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
