//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {

        public Ticket(string seatnum)
        {
            SeatNum = Convert.ToInt32(seatnum);
        }

        public Ticket()
        {
        }

        public Ticket(int? showingID, int? seatNum, int? iD_Client)
        {
            ShowingID = showingID;
            SeatNum = seatNum;
            ID_Client = iD_Client;
        }

        public int ID_Ticket { get; set; }
        public Nullable<int> ShowingID { get; set; }
        public Nullable<int> SeatNum { get; set; }
        public Nullable<int> ID_Client { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ShowingFilm ShowingFilm { get; set; }
    }
}
